Repository HKUDS/LightRAG, pull requests merged in 2025-04, with the labels that each got.

#1242 Feat edge thickness
  README.md
  lightrag_webui/src/components/graph/GraphControl.tsx
  lightrag_webui/src/components/graph/Settings.tsx
  lightrag_webui/src/hooks/useLightragGraph.tsx
  lightrag_webui/src/locales/ar.json
  lightrag_webui/src/locales/en.json
  lightrag_webui/src/locales/fr.json
  lightrag_webui/src/locales/zh.json
  lightrag_webui/src/stores/settings.ts
Labels: ui

#1265 Feat：Nodes of the same type are represented by the same color
  lightrag_webui/src/components/graph/Legend.tsx
  lightrag_webui/src/components/graph/LegendButton.tsx
  lightrag_webui/src/features/GraphViewer.tsx
  lightrag_webui/src/hooks/useLightragGraph.tsx
  lightrag_webui/src/lib/constants.ts
  lightrag_webui/src/locales/ar.json
  lightrag_webui/src/locales/en.json
  lightrag_webui/src/locales/fr.json
  lightrag_webui/src/locales/zh.json
  lightrag_webui/src/stores/graph.ts
  lightrag_webui/src/stores/settings.ts
Labels: ui

#1258 Improve RedisKVStorage: Add Connection Pooling, Error Handling, and Batch Processing
  lightrag/kg/redis_impl.py
  lightrag/operate.py
Labels: good first PR

#1447 Improve parallel handling for documents processing
  lightrag/api/routers/document_routes.py
  lightrag/lightrag.py
Labels: Server
